oracle:
    username: "username"
    host: "TNSNAMES.ALIAS" # e.g. MYDB.WORLD
    password: "mypassword"
    mode: "thick" # or thin - if omitted, defaults to thin

snowflake:
    username: "username"
    database: "DBNAME"
    schema: "SCHEMANAME"
    account: "abcdefg-hi12345"
    password: "myotherpassword"

postgres:
    username: "username"
    host: "localhost"
    password: "jlsjrl0rdg0je4"
    database: "dbname"
    port: 5432